version: "3.3"
services:
  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    volumes:
      - ./docker/requirements-local.txt:/app/requirements-local.txt
    environment:
      - SUPERSET_LOAD_EXAMPLES=yes
      - SUPERSET_PLUGINS=["'clickhouse.connect'"]
    command:
      "bash -c 'pip install -r /app/requirements-local.txt && /usr/bin/docker-entrypoint.sh'"
